const fs = require('fs');
const path = require('path');

// サンプル問題から追加する用語
const newTerms = [
  {
    id: "twos_complement",
    term: "2の補数",
    fullName: "Two's Complement",
    meaning: "負数を2進数で表現する方法",
    category: "technology",
    subcategory: "基礎理論",
    description: "コンピュータで負の整数を表現する最も一般的な方法。ビットを反転（1の補数）して1を加えることで得られる。これにより、加算回路だけで減算も実現できる。",
    examples: ["8ビットで-1は11111111", "8ビットで-128は10000000", "符号付き整数の演算"],
    relatedTerms: ["binary_conversion"],
    tips: "「全ビット反転＋1」と覚えろ！-nを求めるにはnのXOR 11111111 + 1だ！"
  },
  {
    id: "binary_conversion",
    term: "2進変換",
    fullName: "Binary Conversion",
    meaning: "10進数と2進数の相互変換",
    category: "technology",
    subcategory: "基礎理論",
    description: "10進数を2進数に変換するには2で割り続けて余りを逆順に並べる。2進数を10進数に変換するには各桁に2の累乗を掛けて合計する。",
    examples: ["10(10進)→1010(2進)", "1011(2進)→11(10進)", "商と余りを使った変換"],
    relatedTerms: ["twos_complement"],
    tips: "10進→2進は「2で割って余りを逆に」、2進→10進は「各桁×2^n」だ！"
  },
  {
    id: "propositional_logic",
    term: "命題論理",
    fullName: "Propositional Logic",
    meaning: "真偽を判定できる文（命題）の論理",
    category: "technology",
    subcategory: "基礎理論",
    description: "AND、OR、NOT、含意（→）などの論理演算を用いて命題の真偽を判定する。プログラミングの条件分岐やデジタル回路の基礎となる。",
    examples: ["P AND Q", "NOT P OR Q", "P → Q（PならばQ）"],
    relatedTerms: [],
    tips: "「PならばQ」=「NOT P OR Q」だ！Pが偽ならQは何でもOKと覚えろ！"
  },
  {
    id: "automaton",
    term: "オートマトン",
    fullName: "Automaton",
    meaning: "入力に応じて状態を遷移する抽象的な機械",
    category: "technology",
    subcategory: "基礎理論",
    description: "有限個の状態と、入力による状態遷移規則を持つ計算モデル。正規表現やコンパイラの字句解析、プロトコル検証などに応用される。",
    examples: ["自動販売機の状態遷移", "正規表現のマッチング", "通信プロトコルの検証"],
    relatedTerms: [],
    tips: "状態遷移図を追いかけろ！入力→現在状態→次状態・出力の流れだ！"
  },
  {
    id: "array_operation",
    term: "配列操作",
    fullName: "Array Operation",
    meaning: "配列データ構造に対する処理",
    category: "technology",
    subcategory: "アルゴリズム",
    description: "配列の要素の参照、追加、削除、並べ替え、回転などの操作。行列の転置や回転は画像処理でも使用される基本操作。",
    examples: ["配列の90度回転", "転置行列", "要素のシフト"],
    relatedTerms: ["stack", "queue"],
    tips: "配列の回転はインデックスの変換パターンを見つけろ！"
  },
  {
    id: "recursive_function",
    term: "再帰関数",
    fullName: "Recursive Function",
    meaning: "自分自身を呼び出す関数",
    category: "technology",
    subcategory: "アルゴリズム",
    description: "関数の中で自分自身を呼び出すことで、繰り返し処理を実現する手法。基底条件（終了条件）が必要。階乗計算やフィボナッチ数列などで使用。",
    examples: ["f(n)=n+f(n-1)", "階乗：n!=n×(n-1)!", "フィボナッチ数列"],
    relatedTerms: ["stack"],
    tips: "再帰は「基底条件」と「再帰呼び出し」の2つで構成だ！スタックを消費するぞ！"
  },
  {
    id: "coding_standard",
    term: "コーディング規約",
    fullName: "Coding Standard",
    meaning: "プログラムの書き方に関するルール",
    category: "technology",
    subcategory: "ソフトウェア",
    description: "チーム開発で品質と保守性を確保するためのルール。命名規則、インデント、コメントの書き方、エラー処理の方針などを定める。",
    examples: ["変数名はキャメルケース", "エラー処理を必ず記述", "マジックナンバー禁止"],
    relatedTerms: [],
    tips: "「メモリ確保失敗時の処理を書く」が正解の典型パターンだ！"
  },
  {
    id: "interrupt",
    term: "割込み",
    fullName: "Interrupt",
    meaning: "実行中の処理を中断して別の処理を行う仕組み",
    category: "technology",
    subcategory: "コンピュータシステム",
    description: "外部割込み（タイマー、I/O完了など）と内部割込み（ゼロ除算、不正命令など）がある。OSのマルチタスク処理の基盤技術。",
    examples: ["タイマー割込み", "キーボード入力", "ゼロ除算例外"],
    relatedTerms: [],
    tips: "外部割込み=CPU外部から（タイマー等）、内部割込み=プログラム起因（例外）だ！"
  },
  {
    id: "ecc",
    term: "ECC",
    fullName: "Error Correcting Code",
    meaning: "誤り訂正符号",
    category: "technology",
    subcategory: "コンピュータシステム",
    description: "データにビットエラーが発生しても検出・訂正できる符号。サーバ用メモリで使用され、1ビットエラーの訂正と2ビットエラーの検出が可能。",
    examples: ["ECCメモリ", "ハミング符号", "RAID"],
    relatedTerms: [],
    tips: "2^nビットのデータにはn+2ビットの冗長ビットが必要だ！"
  },
  {
    id: "cache_memory",
    term: "キャッシュメモリ",
    fullName: "Cache Memory",
    meaning: "CPUと主記憶の間に置く高速な記憶装置",
    category: "technology",
    subcategory: "コンピュータシステム",
    description: "CPUと主記憶の速度差を埋めるための高速メモリ。SRAMで構成され、よく使うデータを保持してアクセス時間を短縮する。",
    examples: ["L1キャッシュ", "L2キャッシュ", "キャッシュヒット"],
    relatedTerms: ["cache_hit_rate"],
    tips: "実効アクセス時間=ヒット率×キャッシュ時間＋(1-ヒット率)×主記憶時間だ！"
  },
  {
    id: "virtualization",
    term: "仮想化",
    fullName: "Virtualization",
    meaning: "物理リソースを論理的に分割・統合する技術",
    category: "technology",
    subcategory: "コンピュータシステム",
    description: "1台の物理サーバ上で複数の仮想マシンを動作させたり、複数のストレージを1つに見せたりする技術。クラウドの基盤技術。",
    examples: ["仮想マシン（VM）", "コンテナ", "仮想ネットワーク"],
    relatedTerms: ["vdi"],
    tips: "仮想化で資源を効率利用！停止マシンの負荷は残りマシンで分担だ！"
  },
  {
    id: "buffer",
    term: "バッファ",
    fullName: "Buffer",
    meaning: "データを一時的に蓄える記憶領域",
    category: "technology",
    subcategory: "コンピュータシステム",
    description: "速度差のある装置間でデータをやり取りする際の緩衝領域。送信速度と受信速度の差分がバッファに蓄積される。",
    examples: ["印刷バッファ", "ストリーミングバッファ", "入出力バッファ"],
    relatedTerms: ["queue"],
    tips: "送信S>受信Rなら、T秒後のバッファ必要量=(S-R)×Tだ！"
  },
  {
    id: "interpreter",
    term: "インタプリタ",
    fullName: "Interpreter",
    meaning: "ソースコードを1行ずつ解釈実行するプログラム",
    category: "technology",
    subcategory: "ソフトウェア",
    description: "プログラムを機械語に一括変換せず、実行時に1命令ずつ解釈・実行する方式。開発・デバッグが容易だが実行速度は遅い。",
    examples: ["Python", "JavaScript", "Ruby"],
    relatedTerms: [],
    tips: "インタプリタ=逐次解釈実行、コンパイラ=一括翻訳だ！"
  },
  {
    id: "file_allocation",
    term: "ファイル割当て",
    fullName: "File Allocation",
    meaning: "ファイルを記憶媒体に配置する方法",
    category: "technology",
    subcategory: "ソフトウェア",
    description: "ディスク等にファイルを割り当てる方式。空き領域が最大の媒体を選ぶ「最大空き領域法」などがある。",
    examples: ["連続割当て", "リンク割当て", "索引割当て"],
    relatedTerms: [],
    tips: "最大空き領域法は空きが一番多いところに割り当てるぞ！"
  },
  {
    id: "file_path",
    term: "ファイルパス",
    fullName: "File Path",
    meaning: "ファイルの場所を示す文字列",
    category: "technology",
    subcategory: "ソフトウェア",
    description: "絶対パス（ルートから）と相対パス（カレントディレクトリから）がある。ディレクトリ階層を区切り文字で連結して表現。",
    examples: ["/home/user/file.txt", "../data/config.json", "C:\\Users\\file.txt"],
    relatedTerms: [],
    tips: "絶対パス=ルート（/）から、相対パス=現在地からだ！"
  },
  {
    id: "dram",
    term: "DRAM",
    fullName: "Dynamic Random Access Memory",
    meaning: "コンデンサで記憶する揮発性メモリ",
    category: "technology",
    subcategory: "コンピュータシステム",
    description: "1トランジスタ+1コンデンサの単純構造で高集積化・低コスト。定期的なリフレッシュが必要。主記憶（RAM）に使用。",
    examples: ["DDR4", "DDR5", "SDRAM"],
    relatedTerms: [],
    tips: "DRAM=高集積・安い・リフレッシュ必要、SRAM=高速・高い・リフレッシュ不要だ！"
  },
  {
    id: "input_check",
    term: "入力チェック",
    fullName: "Input Validation",
    meaning: "入力データの妥当性を検証する処理",
    category: "technology",
    subcategory: "データベース",
    description: "論理チェック（データ間の整合性）、フォーマットチェック（形式）、範囲チェック、重複チェックなどがある。",
    examples: ["日付の妥当性", "数値の範囲", "必須項目のチェック"],
    relatedTerms: [],
    tips: "論理チェック=データ間の関係性、フォーマットチェック=形式だ！"
  },
  {
    id: "view",
    term: "ビュー",
    fullName: "View",
    meaning: "データベースの仮想的な表",
    category: "technology",
    subcategory: "データベース",
    description: "基底表から導出される仮想表。実データを持たず、定義（SELECT文）に基づいて動的に生成。アクセス制御やデータの抽象化に使用。",
    examples: ["CREATE VIEW sales_summary AS SELECT ...", "機密列を隠すビュー", "複数表を結合したビュー"],
    relatedTerms: ["projection"],
    tips: "ビュー=名前付き導出表！ビューの上にビューも定義できるぞ！"
  },
  {
    id: "uml",
    term: "UML",
    fullName: "Unified Modeling Language",
    meaning: "オブジェクト指向のモデリング言語",
    category: "technology",
    subcategory: "システム開発",
    description: "システムの構造や振る舞いを図で表現する標準記法。クラス図、シーケンス図、ユースケース図などがある。",
    examples: ["クラス図", "シーケンス図", "アクティビティ図"],
    relatedTerms: ["er_model"],
    tips: "多重度の読み方：1..*は「1以上」、0..*は「0以上」だ！"
  },
  {
    id: "data_lake",
    term: "データレイク",
    fullName: "Data Lake",
    meaning: "あらゆる形式のデータを生のまま格納する貯蔵庫",
    category: "technology",
    subcategory: "データベース",
    description: "構造化・非構造化データを変換せずそのまま保存。スキーマオンリード方式で、分析時にスキーマを適用する。ビッグデータ分析の基盤。",
    examples: ["ログファイル", "センサーデータ", "ソーシャルメディアデータ"],
    relatedTerms: ["structured_data", "unstructured_data"],
    tips: "データレイク=生データのまま格納、データウェアハウス=整形して格納だ！"
  },
  {
    id: "projection",
    term: "射影",
    fullName: "Projection",
    meaning: "表から特定の列を取り出す関係演算",
    category: "technology",
    subcategory: "データベース",
    description: "関係代数の基本演算。表から必要な属性（列）だけを抽出する。SQLのSELECT句で列名を指定することに相当。",
    examples: ["SELECT name, age FROM users", "商品番号と数量だけを取り出す"],
    relatedTerms: ["view"],
    tips: "射影=列の抽出、選択=行の抽出だ！混同するな！"
  },
  {
    id: "ble",
    term: "BLE",
    fullName: "Bluetooth Low Energy",
    meaning: "低消費電力の近距離無線通信規格",
    category: "technology",
    subcategory: "ネットワーク",
    description: "Bluetooth 4.0以降で導入された省電力モード。IoTデバイス、ウェアラブル機器、ビーコンなどで広く使用される。",
    examples: ["スマートウォッチ", "IoTセンサー", "ビーコン"],
    relatedTerms: [],
    tips: "BLE=Bluetooth省電力版、PAN（Personal Area Network）で使うぞ！"
  },
  {
    id: "transmission_time",
    term: "伝送時間",
    fullName: "Transmission Time",
    meaning: "データを転送するのにかかる時間",
    category: "technology",
    subcategory: "ネットワーク",
    description: "伝送時間=データ量÷実効伝送速度。伝送効率を考慮する場合は、理論速度×効率で実効速度を求める。",
    examples: ["12MB÷1.5Mbps（効率50%）=128秒"],
    relatedTerms: ["bps"],
    tips: "バイトとビットに注意！1バイト=8ビットだ！効率も忘れるな！"
  },
  {
    id: "mime",
    term: "MIME",
    fullName: "Multipurpose Internet Mail Extensions",
    meaning: "電子メールで様々なデータを送信するための規格",
    category: "technology",
    subcategory: "ネットワーク",
    description: "元々テキストのみだったメールで、画像・音声・バイナリなど様々な形式を添付可能にする拡張規格。Content-Typeで種類を指定。",
    examples: ["image/jpeg", "application/pdf", "text/html"],
    relatedTerms: [],
    tips: "MIME=メール添付の規格、SMTP=メール送信のプロトコルだ！"
  },
  {
    id: "udp",
    term: "UDP",
    fullName: "User Datagram Protocol",
    meaning: "コネクションレス型のトランスポート層プロトコル",
    category: "technology",
    subcategory: "ネットワーク",
    description: "TCPと異なり、接続確立や再送制御を行わない。オーバーヘッドが小さく高速だが、信頼性は保証しない。リアルタイム通信向け。",
    examples: ["動画ストリーミング", "オンラインゲーム", "VoIP"],
    relatedTerms: [],
    tips: "UDP=高速・低信頼性・リアルタイム向け、TCP=低速・高信頼性だ！"
  },
  {
    id: "port_number",
    term: "ポート番号",
    fullName: "Port Number",
    meaning: "通信のアプリケーションを識別する番号",
    category: "technology",
    subcategory: "ネットワーク",
    description: "0-65535の範囲。ウェルノウンポート（0-1023）はHTTP:80、HTTPS:443など標準サービス用。戻りパケットでは送信元と宛先が入れ替わる。",
    examples: ["HTTP:80", "HTTPS:443", "SSH:22"],
    relatedTerms: [],
    tips: "戻りパケットは送信元・宛先が逆になるぞ！"
  },
  {
    id: "social_engineering",
    term: "ソーシャルエンジニアリング",
    fullName: "Social Engineering",
    meaning: "人間の心理的な隙を突いて情報を入手する手法",
    category: "technology",
    subcategory: "セキュリティ",
    description: "技術的な攻撃ではなく、なりすまし、緊急事態を装う、肩越しに覗く（ショルダーハッキング）などで機密情報を入手する。",
    examples: ["なりすまし電話", "ショルダーハッキング", "ゴミ箱漁り（トラッシング）"],
    relatedTerms: [],
    tips: "技術じゃなく人を騙す！緊急事態を装ってパスワードを聞き出すのが典型だ！"
  },
  {
    id: "botnet",
    term: "ボットネット",
    fullName: "Botnet",
    meaning: "マルウェアに感染したコンピュータで構成されるネットワーク",
    category: "technology",
    subcategory: "セキュリティ",
    description: "攻撃者がC&Cサーバから指令を出し、感染PC群（ボット）に一斉にスパム送信やDDoS攻撃を実行させる。",
    examples: ["DDoS攻撃", "スパムメール送信", "仮想通貨マイニング"],
    relatedTerms: ["cc_server"],
    tips: "ボットネット=感染PCの軍団、C&Cサーバ=司令塔だ！"
  },
  {
    id: "cc_server",
    term: "C&Cサーバ",
    fullName: "Command and Control Server",
    meaning: "ボットネットを制御する指令サーバ",
    category: "technology",
    subcategory: "セキュリティ",
    description: "マルウェアに感染したPCに対して攻撃命令を送信し、その応答を受け取るサーバ。ボットネット攻撃の中枢。",
    examples: ["攻撃指令の送信", "感染PCの情報収集", "マルウェアの更新配布"],
    relatedTerms: ["botnet"],
    tips: "C&C=Command & Control、ボットネットの「司令塔」だ！"
  },
  {
    id: "mac",
    term: "メッセージ認証符号",
    fullName: "Message Authentication Code",
    meaning: "メッセージの改ざんを検知するための符号",
    category: "technology",
    subcategory: "セキュリティ",
    description: "共有秘密鍵を使ってメッセージから固定長の認証符号を生成。受信者が同じ鍵で再計算し、一致を確認することで改ざんを検知。",
    examples: ["HMAC", "CMAC", "Poly1305"],
    relatedTerms: [],
    tips: "MAC=改ざん検知＋送信者認証、ハッシュだけでは認証できないぞ！"
  },
  {
    id: "ups",
    term: "UPS",
    fullName: "Uninterruptible Power Supply",
    meaning: "無停電電源装置",
    category: "technology",
    subcategory: "セキュリティ",
    description: "停電や瞬断時にバッテリーから電力を供給し、システムの正常シャットダウンまでの時間を確保する。可用性向上に寄与。",
    examples: ["サーバ用UPS", "ネットワーク機器のバックアップ電源"],
    relatedTerms: ["availability"],
    tips: "UPS=停電対策、電源の瞬断によるデータ破損を防ぐ！"
  },
  {
    id: "fuzzing",
    term: "ファジング",
    fullName: "Fuzzing",
    meaning: "異常データを大量に入力して脆弱性を発見する手法",
    category: "technology",
    subcategory: "セキュリティ",
    description: "ソフトウェアに予期しないデータや境界値、異常値を自動的に大量入力し、クラッシュや異常動作を監視して脆弱性を発見する。",
    examples: ["バッファオーバーフロー検出", "入力値バリデーションのテスト"],
    relatedTerms: [],
    tips: "ファジング=異常データ大量投入で脆弱性発見！「ファズ」は「あいまいな」の意だ！"
  },
  {
    id: "malware_analysis",
    term: "マルウェア解析",
    fullName: "Malware Analysis",
    meaning: "悪意あるソフトウェアの動作を調査すること",
    category: "technology",
    subcategory: "セキュリティ",
    description: "静的解析（コード分析）と動的解析（実行監視）がある。動的解析はサンドボックスで実行し、ファイル操作や通信を監視する。",
    examples: ["逆アセンブル", "サンドボックス実行", "ネットワーク通信監視"],
    relatedTerms: [],
    tips: "動的解析=実行して観察、静的解析=実行せずコード分析だ！"
  },
  {
    id: "encapsulation",
    term: "カプセル化",
    fullName: "Encapsulation",
    meaning: "データと操作を一体化し内部を隠蔽すること",
    category: "technology",
    subcategory: "ソフトウェア",
    description: "オブジェクト指向の三大要素の一つ。データ（属性）とメソッド（操作）を一つのクラスにまとめ、外部からは必要なインターフェースだけを公開する。",
    examples: ["privateメンバ変数", "getter/setter", "情報隠蔽"],
    relatedTerms: ["polymorphism"],
    tips: "カプセル化=データ＋操作を包んで隠す！実装の詳細を見せないぞ！"
  },
  {
    id: "module_coupling",
    term: "モジュール結合度",
    fullName: "Module Coupling",
    meaning: "モジュール間の依存関係の強さ",
    category: "technology",
    subcategory: "ソフトウェア",
    description: "結合度は弱いほど良い。データ結合（必要なデータのみ引数で渡す）が最も弱く、内容結合（内部を直接参照）が最も強い。",
    examples: ["データ結合", "スタンプ結合", "制御結合", "共通結合"],
    relatedTerms: [],
    tips: "結合度は弱いほど良い！「引数でデータだけ渡す」が最弱だ！"
  },
  {
    id: "black_box_test",
    term: "ブラックボックステスト",
    fullName: "Black Box Test",
    meaning: "内部構造を考慮せず仕様に基づいてテストする手法",
    category: "technology",
    subcategory: "システム開発",
    description: "プログラムの内部構造を見ずに、入力と出力の関係（仕様）に基づいてテストケースを作成。同値分割法や境界値分析などの技法がある。",
    examples: ["同値分割法", "境界値分析", "デシジョンテーブル"],
    relatedTerms: [],
    tips: "ブラックボックス=中身を見ない、ホワイトボックス=中身を見るテストだ！"
  },
  {
    id: "sprint",
    term: "スプリント",
    fullName: "Sprint",
    meaning: "スクラムにおける固定期間の開発サイクル",
    category: "management",
    subcategory: "プロジェクトマネジメント",
    description: "1〜4週間の固定期間で、リリース可能なプロダクトインクリメントを作成する。期間中はゴールを変更せず、終了時にレビューと振り返りを行う。",
    examples: ["2週間スプリント", "スプリントプランニング", "スプリントレビュー"],
    relatedTerms: ["scrum", "product_owner", "scrum_master"],
    tips: "スプリント=固定期間の開発サイクル、毎回動くソフトを作るぞ！"
  },
  {
    id: "project_lifecycle",
    term: "プロジェクトライフサイクル",
    fullName: "Project Life Cycle",
    meaning: "プロジェクトの開始から終了までの一連のフェーズ",
    category: "management",
    subcategory: "プロジェクトマネジメント",
    description: "一般に、開始→計画→実行→終結の流れ。進むにつれてリスクは減少し、変更コストは増加。ステークホルダの影響力は初期が最大。",
    examples: ["立ち上げ", "計画", "実行", "終結"],
    relatedTerms: [],
    tips: "後になるほどリスク減少・変更コスト増加だ！"
  },
  {
    id: "function_point",
    term: "ファンクションポイント法",
    fullName: "Function Point Method",
    meaning: "機能量からソフトウェア規模を見積もる手法",
    category: "management",
    subcategory: "プロジェクトマネジメント",
    description: "外部入力・外部出力・外部照会・内部論理ファイル・外部インタフェースファイルの数と複雑度から規模を算出。言語非依存で見積もり可能。",
    examples: ["入出力画面数のカウント", "ファイル数のカウント"],
    relatedTerms: [],
    tips: "FP法=機能（入出力・ファイル）の数と複雑さで見積もるぞ！"
  },
  {
    id: "benchmarking",
    term: "ベンチマーキング",
    fullName: "Benchmarking",
    meaning: "優良事例と比較して改善点を見つける手法",
    category: "management",
    subcategory: "サービスマネジメント",
    description: "業界内外のベストプラクティスと自社のプロセスやパフォーマンスを比較し、差異を分析して改善につなげる手法。",
    examples: ["他社との品質比較", "業界標準との比較"],
    relatedTerms: [],
    tips: "ベンチマーキング=ベストプラクティスと比較して改善点を発見だ！"
  },
  {
    id: "rollforward",
    term: "ロールフォワード",
    fullName: "Roll Forward",
    meaning: "バックアップ後の更新をログから再適用して回復する方法",
    category: "management",
    subcategory: "サービスマネジメント",
    description: "ディスク障害時に、フルバックアップからリストア後、トランザクションログを使って障害直前の状態まで回復する。",
    examples: ["データベース障害復旧", "ログ適用による前進回復"],
    relatedTerms: [],
    tips: "ロールフォワード=バックアップ＋ログで前進回復、ロールバック=更新前に戻すだ！"
  },
  {
    id: "system_audit",
    term: "システム監査",
    fullName: "System Audit",
    meaning: "情報システムの適切性を第三者が検証すること",
    category: "management",
    subcategory: "システム監査",
    description: "情報システムの信頼性・安全性・効率性を、独立した立場から客観的に点検・評価する。監査人の独立性確保が重要。",
    examples: ["セキュリティ監査", "内部統制監査", "ITガバナンス監査"],
    relatedTerms: ["security_audit"],
    tips: "監査人は内部監査部門に所属させて独立性を確保だ！"
  },
  {
    id: "vdi",
    term: "VDI",
    fullName: "Virtual Desktop Infrastructure",
    meaning: "デスクトップ環境をサーバ上で仮想化する技術",
    category: "strategy",
    subcategory: "システム戦略",
    description: "PCのデスクトップ環境をサーバ上で動作させ、端末からネットワーク経由でアクセスする。テレワークやBYOD対応に有効。",
    examples: ["シンクライアント", "テレワーク環境"],
    relatedTerms: ["virtualization"],
    tips: "VDI=デスクトップをサーバに置いて、どこからでもアクセスだ！"
  },
  {
    id: "roi",
    term: "ROI",
    fullName: "Return On Investment",
    meaning: "投資収益率",
    category: "strategy",
    subcategory: "経営戦略",
    description: "投資に対してどれだけの利益が得られたかを示す指標。ROI=(利益-投資額)/投資額×100%。投資効果の評価に使用。",
    examples: ["IT投資の評価", "マーケティング効果測定"],
    relatedTerms: [],
    tips: "ROI=(利益-投資)/投資×100%だ！高いほど効率の良い投資！"
  },
  {
    id: "green_purchase",
    term: "グリーン購入",
    fullName: "Green Purchasing",
    meaning: "環境負荷の少ない製品・サービスを優先購入すること",
    category: "strategy",
    subcategory: "経営戦略",
    description: "環境への配慮を購入基準に加え、環境ラベル認定製品などを優先的に購入する取り組み。グリーン購入法で国等に義務付け。",
    examples: ["エコマーク製品", "省エネ機器", "再生紙"],
    relatedTerms: ["carbon_footprint"],
    tips: "グリーン購入=環境に優しい製品を選ぶ購買行動だ！"
  },
  {
    id: "lean_startup",
    term: "リーンスタートアップ",
    fullName: "Lean Startup",
    meaning: "最小限の製品で素早く市場検証する起業手法",
    category: "strategy",
    subcategory: "経営戦略",
    description: "エリック・リース提唱。MVP（実用最小限の製品）を素早く作り、Build-Measure-Learn（構築・計測・学習）のフィードバックループで改善を繰り返す。",
    examples: ["MVP開発", "ピボット（方向転換）", "検証済み学習"],
    relatedTerms: [],
    tips: "リーンスタートアップ=最小製品で仮説検証→改善のサイクルを回すぞ！"
  },
  {
    id: "hems",
    term: "HEMS",
    fullName: "Home Energy Management System",
    meaning: "家庭内のエネルギー管理システム",
    category: "strategy",
    subcategory: "ビジネスインダストリ",
    description: "家庭内の太陽光発電、蓄電池、家電などをネットワーク接続し、エネルギー消費の可視化と最適制御を行うシステム。",
    examples: ["電力使用量の見える化", "家電の自動制御", "太陽光発電の管理"],
    relatedTerms: [],
    tips: "HEMS=Home（家庭）のエネルギー管理、BEMS=ビル、FEMS=工場だ！"
  },
  {
    id: "cgm",
    term: "CGM",
    fullName: "Consumer Generated Media",
    meaning: "消費者が作成するメディアコンテンツ",
    category: "strategy",
    subcategory: "ビジネスインダストリ",
    description: "ブログ、SNS、口コミサイト、動画投稿サイトなど、一般消費者が情報を発信するメディアの総称。マーケティングで重要視される。",
    examples: ["ブログ", "口コミサイト", "SNS投稿"],
    relatedTerms: [],
    tips: "CGM=Consumer（消費者）が作るメディアだ！企業発信ではないぞ！"
  },
  {
    id: "linear_programming",
    term: "線形計画法",
    fullName: "Linear Programming",
    meaning: "制約条件下で目的関数を最適化する手法",
    category: "strategy",
    subcategory: "企業活動",
    description: "線形の制約条件と目的関数を持つ最適化問題を解く手法。資源配分、生産計画、輸送問題などに応用される。",
    examples: ["生産量の最適化", "輸送コストの最小化"],
    relatedTerms: [],
    tips: "制約条件を満たす領域の頂点をチェックして最適解を探すぞ！"
  },
  {
    id: "depreciation",
    term: "減価償却",
    fullName: "Depreciation",
    meaning: "固定資産の価値減少を費用として計上すること",
    category: "strategy",
    subcategory: "企業活動",
    description: "建物、機械、車両などの固定資産は時間とともに価値が減少する。定額法（毎年同額）や定率法（残存価額に一定率）で費用配分。",
    examples: ["PC購入費の4年間償却", "建物の減価償却"],
    relatedTerms: [],
    tips: "定額法=取得価額×償却率、帳簿価額=取得価額-累計償却額だ！"
  },
  {
    id: "break_even_point",
    term: "損益分岐点",
    fullName: "Break Even Point",
    meaning: "売上高と総費用が等しくなる点",
    category: "strategy",
    subcategory: "企業活動",
    description: "利益がゼロになる売上高。これを超えると利益が出る。損益分岐点売上高=固定費÷(1-変動費率)で計算。",
    examples: ["新製品の採算ライン", "最低必要売上高の算出"],
    relatedTerms: [],
    tips: "損益分岐点=固定費/(1-変動費率)、目標利益時は(固定費+目標利益)/(1-変動費率)だ！"
  },
  {
    id: "worker_dispatch",
    term: "労働者派遣",
    fullName: "Worker Dispatching",
    meaning: "派遣元が雇用する労働者を派遣先に派遣すること",
    category: "strategy",
    subcategory: "法務",
    description: "労働者は派遣元と雇用契約を結び、派遣先からは指揮命令を受ける。請負とは異なり、派遣先が直接指揮命令できる。",
    examples: ["IT技術者派遣", "事務派遣"],
    relatedTerms: [],
    tips: "派遣=派遣先が指揮命令、請負=請負元が指揮命令だ！図の関係を覚えろ！"
  }
];

// glossary.jsonを読み込み
const glossaryPath = path.join(__dirname, '../data/glossary.json');
const data = JSON.parse(fs.readFileSync(glossaryPath, 'utf8'));

// 新しい用語を追加
data.terms = data.terms.concat(newTerms);

// ファイルに書き込み
fs.writeFileSync(glossaryPath, JSON.stringify(data, null, 2), 'utf8');

console.log('新しい用語を追加しました。');
console.log('現在の総用語数:', data.terms.length);
